// Import necessary dependencies and components
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components_new/TopBar/TopBar";
import { ThemeProvider } from "./context/ThemeContext";

// Configure Geist Sans font with Latin subset
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure Geist Mono (monospace) font with Latin subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the application (SEO and browser tab information)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component that wraps all pages
// This component provides the basic HTML structure and global providers
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply font variables and antialiasing for better text rendering
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ThemeProvider wraps the app for dark/light theme functionality */}
        <ThemeProvider>
          {/* TopBar component for navigation */}
          <TopBar />
          {/* Render page content */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
